replicaCount: 1

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}