apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-email-hom
  labels:
    app: api-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-email
  template:
    metadata:
      labels:
        app: api-email
    spec:
      containers:
      - name: api-email
        image: sa-saopaulo-1.ocir.io/gr5hyv2ifg8g/api-email:hom-20260204_1535
        envFrom:
        - configMapRef:
            name: api-email-env
            optional: false
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 5m
        livenessProbe:
          httpGet:
            path: /api-email/verifica-disponibilidade
            port: 8080
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api-email/verifica-disponibilidade
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /opt/glowroot
          name: nfs-glowroot
      imagePullSecrets:
      - name: ocirsecret
      volumes:
      - name: nfs-glowroot
        nfs:
          path: /exports/glowroot
          server: 172.20.4.5
