apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-email
  name: api-email-hom
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-email
  sessionAffinity: None
  type: ClusterIP
