name: Teste CI

on: [push]

jobs:

  job_config:

    runs-on: ubuntu-latest
    outputs:
      lista-juntas: ${{ steps.listar-juntas.outputs.lista-juntas }}
      sha_short: ${{ steps.listar-juntas.outputs.sha_short }}
      branch: ${{ steps.listar-juntas.outputs.branch }}

    steps:
    - id: listar-juntas
      run: |
        commit_message=$(echo "${{ github.event.head_commit.message }}" | grep "\[ambientes\]")
        echo ${commit_message##*:}
        JSON_STRING=$(echo ${commit_message##*:} | tr ',' '\n' | jq -R . | jq -c -s .)
        echo "lista-juntas=$JSON_STRING" >> "$GITHUB_OUTPUT"

    - name: job_info
      id: job_info
      run: |
        set -x

        echo "sha_short=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_OUTPUT"
        echo "$sha_short"
        echo "$branch"
        echo "$GITHUB_OUTPUT"

    
  build:
    runs-on: ubuntu-latest
    needs: job_config
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: teste
        run: |
          echo "Workspace: ${{ github.workspace }}"

  config_commit:
    runs-on: ubuntu-latest
    needs: [job_config, build]
    env:
      SHA_SHORT: ${{ needs.job_config.outputs.sha_short }}
      BRANCH: ${{ needs.job_config.outputs.branch }}
    strategy:
      matrix:
        item: ${{ fromJSON(needs.job_config.outputs.lista-juntas) }}
    steps:
      - name: Process item
        run: |
          echo "Processing item: ${{ matrix.item }}"
          echo "SHA_SHORT: $SHA_SHORT"
          echo "BRANCH: $BRANCH"
